# Generated by Django 4.2.7 on 2023-12-13 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Employee name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Employee Email')),
                ('adress', models.TextField(max_length=500, verbose_name='Employee Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Employee Phone')),
                ('doj', models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Date of joining')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Employee Salary')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
    ]
