# Generated by Django 4.2.7 on 2023-12-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('other', 'other')], default='Male', max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.FileField(default='employee/blank.jpg', upload_to='employee', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Salary'),
        ),
    ]
